# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1952d4e3eec294328df9f73b6f0b5c1153fa91efaa46547dba52731e9e6fc2cead2df3f85b996164486631bd752a7c15c208c8fe75e64bf80a73d9c7d748f886

test:
  secret_key_base: 899feddefead72686d7a2467f30d70de57e84b5e69f906e31ca9c936110bcc30b0fc0479ce3c79921043b907e86e353fe410f388c26847893e1d66b6c4aefd6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
